/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author noora
 */
public class MemberList extends javax.swing.JFrame {

    /**
     * Creates new form MemberList
     */
    public MemberList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        unassignFrom = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        assignTo = new javax.swing.JButton();
        deleteMem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        updatemem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addmem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Georgia Pro Cond Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Unassign from trainer");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 180, 40));

        jLabel8.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Back");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 80, 20));

        back.setBackground(new java.awt.Color(204, 153, 255));
        back.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/button.png"))); // NOI18N
        back.setText("Member");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 80, 20));

        unassignFrom.setBackground(new java.awt.Color(204, 153, 255));
        unassignFrom.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 24)); // NOI18N
        unassignFrom.setForeground(new java.awt.Color(255, 255, 255));
        unassignFrom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/button.png"))); // NOI18N
        unassignFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unassignFromActionPerformed(evt);
            }
        });
        getContentPane().add(unassignFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 180, 40));
        addmem.setOpaque(false);
        addmem.setContentAreaFilled(false);
        addmem.setBorderPainted(false);

        jLabel5.setFont(new java.awt.Font("Georgia Pro Cond Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Delete member");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 40));

        jLabel6.setFont(new java.awt.Font("Georgia Pro Cond Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Assign to trainer");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 180, 40));

        assignTo.setBackground(new java.awt.Color(204, 153, 255));
        assignTo.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 24)); // NOI18N
        assignTo.setForeground(new java.awt.Color(255, 255, 255));
        assignTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/button.png"))); // NOI18N
        assignTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToActionPerformed(evt);
            }
        });
        getContentPane().add(assignTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 180, 40));
        addmem.setOpaque(false);
        addmem.setContentAreaFilled(false);
        addmem.setBorderPainted(false);

        deleteMem.setBackground(new java.awt.Color(204, 153, 255));
        deleteMem.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 24)); // NOI18N
        deleteMem.setForeground(new java.awt.Color(255, 255, 255));
        deleteMem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/button.png"))); // NOI18N
        deleteMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMemActionPerformed(evt);
            }
        });
        getContentPane().add(deleteMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 40));
        addmem.setOpaque(false);
        addmem.setContentAreaFilled(false);
        addmem.setBorderPainted(false);

        jLabel4.setFont(new java.awt.Font("Georgia Pro Cond Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Update member");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, 40));

        updatemem.setBackground(new java.awt.Color(204, 153, 255));
        updatemem.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 24)); // NOI18N
        updatemem.setForeground(new java.awt.Color(255, 255, 255));
        updatemem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/button.png"))); // NOI18N
        updatemem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatememActionPerformed(evt);
            }
        });
        getContentPane().add(updatemem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, 40));
        addmem.setOpaque(false);
        addmem.setContentAreaFilled(false);
        addmem.setBorderPainted(false);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Member");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia Pro Cond Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add new member");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, 40));

        addmem.setBackground(new java.awt.Color(204, 153, 255));
        addmem.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 24)); // NOI18N
        addmem.setForeground(new java.awt.Color(255, 255, 255));
        addmem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/button.png"))); // NOI18N
        addmem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmemActionPerformed(evt);
            }
        });
        getContentPane().add(addmem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, 40));
        addmem.setOpaque(false);
        addmem.setContentAreaFilled(false);
        addmem.setBorderPainted(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/member1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addmemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmemActionPerformed
        // TODO add your handling code here:
        new addnewmember().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addmemActionPerformed

    private void updatememActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatememActionPerformed
        // TODO add your handling code here:
        new updatememberID().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_updatememActionPerformed

    private void deleteMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMemActionPerformed
        // TODO add your handling code here:
        new deleteMember1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_deleteMemActionPerformed

    private void assignToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToActionPerformed
        // TODO add your handling code here:
        new assignTrainer1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_assignToActionPerformed

    private void unassignFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unassignFromActionPerformed
        // TODO add your handling code here:
        new UnassignorChange().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_unassignFromActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new mainmenu2().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmem;
    private javax.swing.JButton assignTo;
    private javax.swing.JButton back;
    private javax.swing.JButton deleteMem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton unassignFrom;
    private javax.swing.JButton updatemem;
    // End of variables declaration//GEN-END:variables
}
